{
 "title": "process-exporter testing",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Panels using process-exporter data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Per Thread CPU Usage : osd.41",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(pid,tname) (rate(ceph_thread_cpu_user_seconds_total{daemon=\"osd.41\"}[30s]) + rate(ceph_thread_cpu_kernel_seconds_total[30s]))",
     "legendFormat": "{{tname}}"
    }
   ]
  },
  {
   "title": "Daemon Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "ceph_process_rss_size_bytes", "legendFormat": "{{daemon}}" }
   ]
  },
  {
   "title": "Daemon CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(ceph_process_cpu_kernel_seconds_total[30s]) + rate(ceph_process_cpu_user_seconds_total[30s])",
     "legendFormat": "{{daemon}}"
    }
   ]
  },
  {
   "title": "Per Thread CPU Usage : mgr",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(pid,tname) (rate(ceph_thread_cpu_user_seconds_total{daemon=~\"mgr.*\"}[30s]) + rate(ceph_thread_cpu_kernel_seconds_total[30s]))",
     "legendFormat": "{{tname}}"
    }
   ]
  },
  {
   "title": "Daemon SysCalls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "(rate(ceph_process_syscall_reads_total[30s]) + rate(ceph_process_syscall_writes_total[30s])) ",
     "legendFormat": "{{daemon}}"
    }
   ]
  },
  {
   "title": "Daemon throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ceph_process_read_bytes_total[30s]) + rate(ceph_process_written_bytes_total[30s])",
     "legendFormat": "{{daemon}}"
    }
   ]
  }
 ]
}